dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.2
    - pooltogether/owner-manager-contracts@1.1.0
    - pooltogether/pooltogether-rng-contracts@1.4.0
    - pooltogether/yield-source-interface@1.3.0
compiler:
    solc:
        remappings:
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
            - '@pooltogether/owner-manager-contracts=pooltogether/owner-manager-contracts@1.1.0'
            - '@pooltogether/pooltogether-rng-contracts=pooltogether/pooltogether-rng-contracts@1.4.0'
            - '@pooltogether/yield-source-interface=pooltogether/yield-source-interface@1.3.0'
dotenv: .env
wallets:
    from_key: ${PRIVATE_KEY}
